<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= ucfirst($_GET['page']??'dashboard') ?> - Gudang Arsip</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"><style>body{font-family:'Segoe UI';background:#f8f9fa;margin:0;padding:0}.sidebar{height:100vh;position:fixed;top:0;left:0;width:250px;background:#212529;padding-top:20px;z-index:1000}.sidebar .nav-link{color:#adb5bd;padding:12px 20px;margin-bottom:5px;border-radius:5px;display:block;text-decoration:none}.sidebar .nav-link:hover,.sidebar .nav-link.active{background:#0d6efd;color:white}.sidebar .nav-link i{margin-right:10px}.main-content{margin-left:250px;padding:20px}.navbar{background:#343a40;color:white;padding:15px 20px;margin-bottom:20px}.card{background:white;border:none;box-shadow:0 2px 8px rgba(0,0,0,0.1);border-radius:10px;margin-bottom:20px}.card .table{background:white;margin-bottom:0}.card .table th{background:#0d6efd;color:white}.stat-card{background:white;box-shadow:0 2px 8px rgba(0,0,0,0.1);border-radius:10px;padding:20px;text-align:center;margin-bottom:20px}.stat-card h3{margin:0;font-size:2.5rem;color:#0d6efd}</style></head>
<body>
<div class="sidebar"><h4 class="text-center text-white mb-4"><i class="fas fa-warehouse"></i> Gudang Arsip</h4><nav class="nav flex-column"><a class="nav-link <?= ($_GET['page']??'')=='dashboard'?'active':'' ?>" href="../index.php?page=dashboard"><i class="fas fa-tachometer-alt"></i> Dashboard</a><a class="nav-link <?= ($_GET['page']??'')=='archives'?'active':'' ?>" href="../index.php?page=archives"><i class="fas fa-box"></i> Arsip</a><a class="nav-link <?= ($_GET['page']??'')=='warehouses'?'active':'' ?>" href="../index.php?page=warehouses"><i class="fas fa-building"></i> Gudang</a><a class="nav-link <?= ($_GET['page']??'')=='shelves'?'active':'' ?>" href="../index.php?page=shelves"><i class="fas fa-layer-group"></i> Rak</a><a class="nav-link <?= ($_GET['page']??'')=='movements'?'active':'' ?>" href="../index.php?page=movements"><i class="fas fa-exchange-alt"></i> Pindah</a><a class="nav-link <?= ($_GET['page']??'')=='borrowings'?'active':'' ?>" href="../index.php?page=borrowings"><i class="fas fa-hand-holding"></i> Pinjam</a><hr class="text-white my-3"><a class="nav-link <?= ($_GET['page']??'')=='accounts'?'active':'' ?>" href="../index.php?page=accounts"><i class="fas fa-users"></i> Akun</a><a class="nav-link text-danger" href="../index.php?action=logout"><i class="fas fa-sign-out-alt"></i> Keluar</a></nav></div>
<div class="main-content"><div class="navbar"><h5 class="mb-0"><i class="fas fa-user-circle"></i> <?= htmlspecialchars($_SESSION['username']??'') ?></h5><small class="text-white">Role: <?= htmlspecialchars($_SESSION['role']??'') ?></small></div></div>
<?php if(isset($_SESSION['success'])){ ?><div class="alert alert-success"><?= $_SESSION['success']; unset($_SESSION['success']); ?></div><?php } ?>
<?php
$page = $_GET['page'] ?? 'dashboard';
switch($page){
case 'dashboard': ?>
<div class="card"><div class="card-header"><h5>Dashboard</h5></div><div class="card-body"><p>Selamat Datang.</p><div class="row"><div class="col-md-3"><div class="stat-card"><h3><?= $stats['archives']??0 ?></h3><small>Arsip</small></div></div><div class="col-md-3"><div class="stat-card"><h3><?= $stats['warehouses']??0 ?></h3><small>Gudang</small></div></div><div class="col-md-3"><div class="stat-card"><h3><?= $stats['shelves']??0 ?></h3><small>Rak</small></div></div><div class="col-md-3"><div class="stat-card"><h3><?= $stats['borrowings_active']??0 ?></h3><small>Peminjaman Aktif</small></div></div></div></div></div>
<?php break; case 'archives': ?>
<div class="card"><div class="card-header"><h5>Arsip</h5></div><div class="card-body"><table class="table"><thead><tr><th>Nama</th><th>Kode</th><th>Aksi</th></tr></thead><tbody><?php foreach($archives??[] as $a){ ?><tr><td><?= esc($a['name']) ?></td><td><?= esc($a['code']) ?></td><td><a href="../index.php?page=archives&action=delete&id=<?= $a['id'] ?>" class="btn btn-danger btn-sm" onclick="return confirm('Hapus?')">Hapus</a></td></tr><?php } ?></tbody></table></div></div>
<?php break; case 'warehouses': ?>
<div class="card"><div class="card-header"><h5>Gudang</h5></div><div class="card-body"><table class="table"><thead><tr><th>Kode</th><th>Nama</th><th>Lokasi</th><th>Aksi</th></tr></thead><tbody><?php foreach($warehouses??[] as $w){ ?><tr><td><?= esc($w['code']) ?></td><td><?= esc($w['name']) ?></td><td><?= esc($w['location']) ?></td><td><a href="../index.php?page=warehouses&action=delete&id=<?= $w['id'] ?>" class="btn btn-danger btn-sm" onclick="return confirm('Hapus?')">Hapus</a></td></tr><?php } ?></tbody></table></div></div>
<?php break; case 'shelves': ?>
<div class="card"><div class="card-header"><h5>Rak</h5></div><div class="card-body"><table class="table"><thead><tr><th>Kode</th><th>Gudang</th><th>Aksi</th></tr></thead><tbody><?php foreach($shelves??[] as $s){ ?><tr><td><?= esc($s['code']) ?></td><td><?= esc($s['warehouse_name']) ?></td><td><a href="../index.php?page=shelves&action=delete&id=<?= $s['id'] ?>" class="btn btn-danger btn-sm" onclick="return confirm('Hapus?')">Hapus</a></td></tr><?php } ?></tbody></table></div></div>
<?php break; default: echo "<div class='alert alert-info'>Halaman dalam pengembangan.</div>"; } ?>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
